# Generated by Django 2.1 on 2018-08-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateField(auto_now=True),
        ),
    ]
